### ISSUE TITLE
[Bug]: Fix the Design Difference

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Git-scm-Clone#1]
**Change Download Window**
The Design of  Downloads Window is different from the original site.

**Expected behavior**
![image](https://user-images.githubusercontent.com/96862518/215352001-6ae551d8-5201-4efa-b32b-a0c7db983939.png)

**Current Behaviour**
![image](https://user-images.githubusercontent.com/96862518/215352025-10be9cb7-61b7-4bd8-b295-5ea7f2808817.png)

**Comment by Manobal-Singh-Bagady** [comment]
The Font and Spacing Seem off fix it too, if you can

Original Site:
![image](https://user-images.githubusercontent.com/96862518/215352503-c627e6bd-161d-443b-8d53-afa91ca6c4e1.png)

Current Site:
![image](https://user-images.githubusercontent.com/96862518/215352535-f83117eb-05a5-4dc7-a0e5-1f35c186ebe5.png)

**Comment by Sehaj-kahlon** [comment]
comment for issue assignment

**Comment by Manobal-Singh-Bagady** [comment]
Alright I have assigned this issue to you👍

> comment for issue assignment
