### ISSUE TITLE
[BUG]: After PR #10 the home page of the website is not looking right.

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Git-scm-Clone#13]
After PR #10, the downloads page was added, but the website's home page needed to look different. The CSS changed in #10 needs to be migrated to a new file.

How it's looking right now:

![Screenshot 2023-02-06 210547](https://user-images.githubusercontent.com/96862518/217018874-8cbe4abb-43f7-4c31-a7d1-3d263e999406.png)

How it is intended to look:

![Screenshot 2023-02-06 210752](https://user-images.githubusercontent.com/96862518/217018920-2d2b195c-e68e-482c-b47b-5dc18979c7a4.png)

**Comment by Chanpreetk03** [comment]
I would like to work on this issue

**Comment by Manobal-Singh-Bagady** [comment]
> I would like to work on this issue

Alright, @Chanpreetk03 is assigning it to you.

**Comment by Chanpreetk03** [comment]
Created a pull request. Please do suggest any improvements if needed. Thanks
