### ISSUE TITLE
[Feature Request]: Make the tagline of the page randomize...

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Git-scm-Clone#5]
![image](https://user-images.githubusercontent.com/96862518/215763581-46ff9908-8fdf-4665-a911-10640ad4ddba.png)

The Original Website's Tagline in the heading is random and changes on every reload,

We need to implement this randomized tagline feature using JavaScript.

**Comment by Chanpreetk03** [comment]
I would like to work on this issue.

**Comment by Manobal-Singh-Bagady** [comment]
> I would like to work on this issue.

Sure @Chanpreetk03, I am assigning this issue to you.

**Comment by Ranjana993** [comment]
Hey, I would like to work on this issue.

**Comment by Chanpreetk03** [comment]
Created a pull request, please review and suggest any changes if needed.

**Comment by Manobal-Singh-Bagady** [comment]
> Hey, I would like to work on this issue.

Good to see your interest, but sorry, @Ranjana993, this issue was already assigned to someone else. You can work on other issues if you want

**Comment by Manobal-Singh-Bagady** [comment]
> Created a pull request, please review and suggest any changes if needed.

Alright, @Chanpreetk03, I have reviewed the PR and requested appropriate changes.
