### ISSUE TITLE
[Bug]: The links to the companies do not go anywhere.

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Git-scm-Clone#8]
![image](https://user-images.githubusercontent.com/96862518/216786110-2f3ccae6-2d5c-4156-8960-6718af9659fe.png)

We need to add links to the company websites, like the original git-scm's page.

**Comment by Nikhil7174** [comment]
Please assign me this issue

**Comment by Manobal-Singh-Bagady** [comment]
> Please assign me this issue

Alright @Nikhil7174 assigning it to you.

**Comment by Astha-Raghuwanshi** [comment]
I have made a pull request resolving this issue

**Comment by Nikhil7174** [comment]
@Manobal-Singh-Bagady I have made a pull request regarding this issue. Please do review it.
