### ISSUE TITLE
[Feature Request]: Need to make the download for windows page.

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Git-scm-Clone#9]
![image](https://user-images.githubusercontent.com/96862518/216788426-57cc0e4f-e4f6-4648-a45f-e80696be7d4d.png)

Need to create the page when the user clicks the Download for Windows button.

**Comment by Vaibhav1808** [comment]
Plaassign this issue to me.

**Comment by Manobal-Singh-Bagady** [comment]
> Plaassign this issue to me.

Alright, @Vaibhav1808, I am assigning this issue to you.
